[tool.ruff]
line-length = 120
target-version = "py312"
lint.select = [
  "E",
  "F",
  "I",
  "N",
  "ASYNC",
  "B",
  "A",
  "COM",
  "DTZ",
  "T20",
  "Q",
  "SIM",
  "TCH",
  "TID",
  "PTH",
  "RUF",
]
lint.ignore = ["RUF013", "E731", "COM812", "B904"]
lint.flake8-annotations.allow-star-arg-any = true
lint.flake8-type-checking.quote-annotations = true
lint.extend-safe-fixes = ["SIM101", "TCH"]
exclude = [".git", ".direnv", ".ruff_cache", "venv"]

[tool.pip-tools]
resolver = "backtracking"
generate-hashes = true
allow_unsafe = true
strip_extras = true

[tool.pyright]
venvPath = "."
venv = "venv/"
